import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";
import Stats from "../components/Pokemon/Stats";

type Props = {
   pokemon: any;
};

export async function getServerSideProps({ query }: any) {
   const link = `https://pokeapi.co/api/v2/pokemon/${query.pokemon}`;
   const res = await fetch(link);
   const data = await res.json();
   return {
      props: { pokemon: data },
   };
}

export default function Pokemon({ pokemon }: Props) {
   console.log(pokemon);
   return (
      <>
         <Head>
            <title>{pokemon.name}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="grid md:grid-cols-2 gap-5 p-7 min-h-screen sm:w-4/5 xl:w-2/3 mx-auto bg-gray-200">
            <motion.div
               exit={{
                  y: 40,
                  opacity: 0,
                  transition: { duration: 0.3 },
               }}
               className="relative aspect-square bg-white rounded-lg shadow-lg"
            >
               <Image
                  src={pokemon.sprites.front_default}
                  layout="fill"
                  priority
               />
               <motion.div
                  initial={{ height: 0 }}
                  animate={{ height: "100%", transition: { duration: 0.5 } }}
                  className="absolute w-full h-full top-0 left-0 bg-white overflow-hidden rounded-lg"
               >
                  <div className="absolute w-full h-full aspect-square top-0 left-0">
                     <div className="w-full aspect-square relative origin-bottom">
                        <Image
                           src={
                              pokemon.sprites.other["official-artwork"]
                                 .front_default
                           }
                           layout="fill"
                           priority
                        />
                     </div>
                  </div>
               </motion.div>
            </motion.div>
            <div className="row-span-2 flex flex-col justify-between">
               <div>Hello</div>
               <div>Hello</div>
               <div>Hello</div>
               <div>Hello</div>
            </div>
            <Stats stats={pokemon.stats} />
         </div>
      </>
   );
}
