import type { NextPage } from "next";
import Head from "next/head";

export async function getServerSideProps() {
   const res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=898");
   const data = await res.json();
   return {
      props: { pokemons: data.results },
   };
}

const Home: NextPage = ({ pokemons }: any) => {
   return (
      <>
         <Head>
            <title>Pokédex</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="w-full sm:w-4/5 xl:w-2/3 bg-gray-100 mx-auto p-5 md:p-7">
            <div className="md:flex space-y-5 md:space-y-0 space-x-0 md:space-x-7 pb-5 md:pb-7">
               <div className="w-full h-10 bg-blue-500"></div>
               <div className="w-full h-10 bg-gray-500"></div>
            </div>
            <div className="min-h-screen w-full grid grid-cols-2 md:grid-cols-4 gap-5 md:gap-7">
               {pokemons.map(({ name }: any, index: number) => (
                  <div
                     key={index}
                     className="bg-gray-300 rounded-lg aspect-square grid place-content-center hover:-translate-y-2 duration-300"
                  >
                     {name}
                  </div>
               ))}
            </div>
         </div>
      </>
   );
};

export default Home;
